AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Operations Assignment using AWS SAM

Globals:
  Function:
    Runtime: python3.11
    Timeout: 900
    MemorySize: 512

Resources:
  AssignmentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "assignment2-s3-operations-${AWS::AccountId}-${AWS::Region}"

  S3OperationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3OperationFullAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt AssignmentBucket.Arn

              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:PutObjectTagging
                  - s3:GetObjectTagging
                  - s3:DeleteObjectTagging
                Resource: !Sub "${AssignmentBucket.Arn}/*"

  S3OperationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-operation-assignment-function
      CodeUri: src/
      Handler: app.lambda_handler
      Role: !GetAtt S3OperationLambdaRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref AssignmentBucket

Outputs:
  BucketName:
    Description: Created S3 Bucket Name
    Value: !Ref AssignmentBucket

  FunctionName:
    Description: Lambda Function Name
    Value: !Ref S3OperationFunction